services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Belsignum\HreflangFallback\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Belsignum\HreflangFallback\EventListener\HreflangFallbackEventListener:
    tags:
      - name: event.listener
        identifier: 'bobtheme/hreflang-fallback'
        after: 'typo3-seo/hreflangGenerator'
        event: TYPO3\CMS\Frontend\Event\ModifyHrefLangTagsEvent
